# Generated by Django 3.0.8 on 2020-07-15 08:40

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('{{cookiecutter.project_label}}_todo', '0002_work_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Note',
            },
        ),
    ]
